[package]
name = "histo"
version = "0.1.0"
authors = ["Thor McAvenia <mcaveniathor@gmail.com>"]
edition = "2018"

[dependencies]
num_cpus = "1.0"
ocl = "0.19"
image = "*"
tui = "0.3.0"
termion = "1.5.1"